---

- name: Install all available dependencies
  apt:
    name: '{{ item }}'
    state: latest
    update_cache: True
  with_items:
    - git
    - vim
    - build-essential
    - libxml2-dev
    - libboost-all-dev
    - cmake
    - libqt4-dev
    - libpthread-workqueue-dev 
    - libglpk-dev
    - graphviz
    - latex2html
    - imagemagick
    - unzip
    - rest2web
    - bison
    - flex
    - doxygen
    # needed for coriolis devel branch
    - bzip2
    - libbz2-dev
    - texlive-fonts-extra
  become: True
  become_method: sudo

- name: Make lemon Dir
  file:
    name: "{{ ansible_env.HOME }}/lemon-1.1.6"
    state: directory

- name: Download and unpack lemon
  unarchive:
    src: "http://lemon.cs.elte.hu/pub/sources/{{ lemonversion }}.zip"
    dest: "{{ ansible_env.HOME }}"
    remote_src: True

- name: Build lemon
  shell: "./configure && make -j"
  args:
    chdir: "{{ ansible_env.HOME }}/{{ lemonversion }}"
    executable: "/bin/bash"

- name: Install lemon
  shell: "make install"
  args:
    chdir: "{{ ansible_env.HOME }}/{{ lemonversion }}"
    executable: "/bin/bash"
  become: True
  become_method: sudo

# only for devel branch of coriolis
- include: roles/coriolis/tasks/rapidjson.yml 

- name: Clone coriolis
  git:
    repo: "{{ coriolisrepo }}"
     # https://github.com/libresilicon/coriolis.git
    dest: "{{ ansible_env.HOME }}/coriolis-2.x/src/coriolis"
    version: "{{ coriolisbranch }}"
    clone: True
    update: True

- name: Build coriolis two time (LaTeX second run)
  shell: "make -j install"
  args:
    chdir: "{{ ansible_env.HOME }}/coriolis-2.x/src/coriolis"
    executable: "/bin/bash"
  ignore_errors: '{{ item }}'
  with_items:
    - True
    - False



